import React from 'react';
import {Grid, IconButton, Container, Typography} from '@material-ui/core';
import SettingsOutlinedIcon from '@material-ui/icons/SettingsOutlined';
import {
  ConversationWrapper,
  GridChatConversation,
  GridIconOptions,
  TestTypography,
} from './ChatConversationStyles';

const ChatConversation = () => {
  return (
    <GridChatConversation item md={7}>
      <ConversationWrapper>
        <Grid direction="row" container>
          <GridIconOptions container justify="flex-end" item md={12}>
            <IconButton color="secondary" aria-label="delete">
              <SettingsOutlinedIcon />
            </IconButton>
          </GridIconOptions>
          <Grid wrap="nowrap" item md={12}>
            <TestTypography>
              DASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASDDASDASFASDASD
            </TestTypography>
          </Grid>
        </Grid>
      </ConversationWrapper>
    </GridChatConversation>
  );
};

export default ChatConversation;
